// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace OOPGUI
{
    public partial class Entry : NSViewController
    {

        private NSViewController _Presentor;

        public NSViewController Presentor
        {
            get { return _Presentor; }
            set { _Presentor = value; }
        }

        public Entry(IntPtr handle) : base(handle)
        {
        }

        private void CloseDialog()
        {
            Presentor.DismissViewController(this);
        }

        partial void BackE(Foundation.NSObject sender)
        {
            RaiseDialogBackE();
            CloseDialog();
        }

        partial void ExitE(Foundation.NSObject sender)
        {
            RaiseDialogExitE();
            CloseDialog();
        }

        public EventHandler DialogBackE;

        internal void RaiseDialogBackE()
        {
            if (this.DialogBackE != null)
                this.DialogBackE(this, EventArgs.Empty);
        }

        public EventHandler DialogExitE;

        internal void RaiseDialogExitE()
        {
            if (this.DialogExitE != null)
                this.DialogExitE(this, EventArgs.Empty);
        }

    }
}
